version: '3.8'

services:
  app:
    image: alexmnsr/discord-esbot:latest
    container_name: discord-esbot
    volumes:
      - .:/discord-esbot
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
    networks:
      - esbot_network

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_LOGIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: always
    networks:
      - esbot_network
    expose:
      - "27017"

  backup:
    build: .
    container_name: mongo-backup
    volumes:
      - ./backups:/backup  # Локальная директория для хранения бэкапов
    depends_on:
      - mongo
    networks:
      - esbot_network
    restart: always

volumes:
  mongo_data:
    external: false

networks:
  esbot_network:
    driver: bridge