services:
  app:
    image: alexmnsr/discord-esbot:latest  # Используйте правильный тег
    container_name: discord-esbot
    volumes:
      - .:/discord-esbot
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo_data: