version: '3.8'

services:
  app:
    image: kusehsup/discord-esbot:latest
    container_name: discord-esbot
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: