version: '3.8'

services:
  app:
    image: alexmnsr/discord-esbot:latest
    container_name: discord-esbot
    volumes:
      - .:/discord-esbot
    depends_on:
      - mongo
    env_file:
      - .env
    restart: always
    networks:
      - esbot-network

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    restart: always
    networks:
      - esbot-network

volumes:
  mongo_data:
    external: false

networks:
  esbot-network:
    driver: bridge