version: '3.8'

services:
  app:
    build: .
    container_name: discord-esbot
    volumes:
      - .:/discord-esbot
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "2356:2356"

volumes:
  mongo_data:
