services:
  app:
    image: alexmnsr/discord-esbot:latest  # Используйте правильный тег
    container_name: discord-esbot
    volumes:
      - .:/discord-esbot
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"  # Порт MongoDB по умолчанию

volumes:
  mongo_data: