name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Убедитесь, что это ваша основная ветка

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: alexmnsr/discord-esbot:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull alexmnsr/discord-esbot:latest
            docker stop discord-esbot || true
            docker rm discord-esbot || true
            docker run -d --name discord-esbot --env-file /.env alexmnsr/discord-esbot:latest
